k-orc/openstack-resource-controller

.github/workflows/go-fmt.yaml, .github/workflows/go-mod.yaml, .github/workflows/go-vet.yaml, .github/workflows/unit.yml
Make PR checks addressable so that they can be set as required.
=> actions: Rename checks

.github/workflows/generate.yaml
=> actions: Check that code generation was run

.github/workflows/container_image.yaml
Also incorporate the changes suggested by @mdbooth in https://github.com/gophercloud/openstack-resource-controller/pull/59
=> Fix build and set an expiration tag for commit images

config/rbac/role.yaml, internal/controller/openstackcloud_controller.go, internal/controller/openstackflavor_controller.go
* Add role for emitting events
* Add group "" to secrets permissions
* Add "patch" to secrets, because secrets do not have the subresource "finalizers"
=> Fix rbac roles

.github/workflows/go-fmt.yaml, .github/workflows/go-mod.yaml, .github/workflows/go-vet.yaml, .github/workflows/unit.yml
Leverage caching in the setup-go action.
Fixes #67
=> actions: Checkout before installing Go

pkg/cloud/cloud.go
Use domain id and name from clouds.yaml
=> clouds: Fix building of Gophercloud auth

.github/workflows/container_image.yaml, .github/workflows/e2e.yaml, .github/workflows/generate.yaml, config/samples/simple-server/kustomization.yaml, config/samples/simple-server/simple-server.yaml
Supersedes #71 (new workflows with secrets are much easier to create from the same repo)
=> ci: e2e test

.github/workflows/e2e.yaml
Test separate OpenStack versions independently.
=> ci: Don't fast-fail e2e jobs

.github/workflows/container_image.yaml
`image:main` becomes `image:branch-main`
=> images: Namespace branch images

api/v1alpha1/openstackserver_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/openstack.k-orc.cloud_openstackservers.yaml, internal/controller/openstackserver_controller.go
The controller will be encoding as appropriate.
=> OpenStackServer: UserData as string

internal/controllers/generic/actuator.go, internal/controllers/generic/dependency.go, internal/controllers/subnet/actuator.go, internal/controllers/subnet/controller.go, internal/controllers/subnet/reconcile.go
=> Update subnet controller to use generic actuator

test/apivalidations/flavor_test.go, test/apivalidations/image_test.go
Flavor Manage policy and import tests
Updated image_test (e.g. use testImageImport instead of testImport)
=> Add more flavor tests validations

.github/workflows/e2e.yaml, Makefile, hack/collectlogs, hack/e2e.sh
Mostly copied from the PoC and adapted to the current structure.
Also includes a collection script, and publishing of artifacts for failed runs.
=> actions: Add basic e2e test exercising cirros example

.dockerignore, .gitignore, Makefile
For testing 'production' deployments in a local kind cluster.
=> Add custom-deploy target

cmd/manager/main.go
This is only tested manually for now.
=> Add --default-ca-certs command line option

api/v1alpha1/common_types.go, api/v1alpha1/controller_options.go, api/v1alpha1/credentials_ref.go, api/v1alpha1/flavor_types.go, api/v1alpha1/image_types.go, api/v1alpha1/network_types.go, api/v1alpha1/port_types.go, api/v1alpha1/router_interface_types.go, api/v1alpha1/router_types.go, api/v1alpha1/securitygroup_types.go, api/v1alpha1/server_types.go, api/v1alpha1/subnet_types.go, cmd/models-schema/zz_generated.openapi.go, config/crd/bases/openstack.k-orc.cloud_flavors.yaml, config/crd/bases/openstack.k-orc.cloud_images.yaml, config/crd/bases/openstack.k-orc.cloud_networks.yaml, config/crd/bases/openstack.k-orc.cloud_ports.yaml, config/crd/bases/openstack.k-orc.cloud_routerinterfaces.yaml, config/crd/bases/openstack.k-orc.cloud_routers.yaml, config/crd/bases/openstack.k-orc.cloud_securitygroups.yaml, config/crd/bases/openstack.k-orc.cloud_servers.yaml, config/crd/bases/openstack.k-orc.cloud_subnets.yaml
First iteration of kal
Fixing issues to make the Kal linter happy.
This is the first iteration as to make sure we minimize the risk of conflicts
and make the review easier.
=> Fix lint issues observed by running Kal

test/apivalidations/flavor_test.go
This ensure that the minimum value is respected for pointers to integer values.
=> Flavors: add a test for filter validation

internal/controllers/generic/controller.go
The generic controller will not proceed with reconciliation unless the
Progressing condition indicates that futher reconciliation is expected.
This dramatically reduces the number of reconciles during resource
provisioning, especially when there are dependencies.
=> Filter reconciles when the resource is up to date

api/v1alpha1/network_types.go, api/v1alpha1/openstack_types.go, config/crd/bases/openstack.k-orc.cloud_flavors.yaml, config/crd/bases/openstack.k-orc.cloud_images.yaml, config/crd/bases/openstack.k-orc.cloud_networks.yaml, config/crd/bases/openstack.k-orc.cloud_ports.yaml, config/crd/bases/openstack.k-orc.cloud_routers.yaml, config/crd/bases/openstack.k-orc.cloud_securitygroups.yaml, config/crd/bases/openstack.k-orc.cloud_servers.yaml, config/crd/bases/openstack.k-orc.cloud_subnets.yaml, test/apivalidations/network_test.go
=> Add network validations

api/v1alpha1/network_types.go
An extra new line broke our linter job.
=> Restore DNSDomain validations

.github/dependabot.yml, .github/workflows/pr-dependabot.yaml
Add dependabot workflow (copied from CAPO) and a basic dependabot config that we can make evolve over time.
=> 🌱 Add dependabot workflow

internal/util/dependency/deletion_guard.go
When a Subnet is created with a router reference, the subnet controller automatically creates a RouterInterface object to represent the attachment. This object is owned by the Subnet directly, not by the actor who created the Subnet.
We only expect actors to delete their own objects. e.g. A user applying and deleting manifests with kustomize:
```
$ kubectl create -k manifests
... and later
$ kubectl delete -k manifests
```
If these manifests created a Subnet, they will not reference the RouterInterface which was created on the Subnet's behalf, and will therefore not delete it.
Previously this situation caused a deadlock:
* Subnet's DeleteResource does not run, because of the presence of the RouterInterface finalizer,
* which is never removed because the owning Subnet has not deleted it,
* …
=> Fix deadlock deleting subnet with router interface

internal/controllers/network/tests/create-full/00-assert.yaml, internal/controllers/network/tests/create-full/00-network.yaml, internal/controllers/network/tests/create-full/01-cleanup.yaml, internal/controllers/network/tests/create-minimal/00-assert.yaml, internal/controllers/network/tests/create-minimal/00-network.yaml, internal/controllers/network/tests/create-minimal/01-assert.yaml, internal/controllers/network/tests/create-minimal/01-cleanup.yaml, internal/controllers/network/tests/import-error/00-assert.yaml, internal/controllers/network/tests/import-error/00-create-networks.yaml, internal/controllers/network/tests/import-error/01-assert.yaml, internal/controllers/network/tests/import-error/01-import-network.yaml, internal/controllers/network/tests/import-error/02-assert.yaml, internal/controllers/network/tests/import-error/02-cleanup.yaml, internal/controllers/network/tests/import/00-import-network.yaml, internal/controllers/network/tests/import/01-assert.yaml, internal/controllers/network/tests/import/01-create-network.yaml
Various changes to bring consistency among tests, and ensuring we're testing the right thing.
=> Fixes to the network kuttl tests

cmd/manager/main.go
The manager code already has the `watchNamespaces` option and actually
configure it already but there is no way for an user to choose what
namespaces to watch.
For example in Hypershift, CAPO (not deployed by the CAPI operator) runs
in a namespace "capi-provider" and we need ORC to watch for the objects
in that namespace; which without this PR is not possible.
This PR adds `--namespaces` which is a comma-separated list of
namespaces that the controller watches to reconcile ORC objects.
This was taken from CAPO manager code.
=> ✨ feat: allow to provide `namespaces` to the manager CLI

internal/controllers/router/actuator.go
We assumed in the router controller that it always had a dependency on a Network object. This is not true as we should be able to create a router with no external gateway.
Fixes #262
=> Router: allow routers without external gateway

api/v1alpha1/image_types.go, cmd/models-schema/zz_generated.openapi.go, config/crd/bases/openstack.k-orc.cloud_images.yaml
=> Set ImageContent.Download as required

internal/controllers/flavor/tests/flavor-import-error/01-assert.yaml, internal/controllers/image/tests/image-import/01-create-trap-image.yaml, internal/controllers/network/tests/network-create-minimal/00-network.yaml, internal/controllers/subnet/tests/subnet-create-minimal-v4/00-subnet.yaml, internal/controllers/subnet/tests/subnet-create-minimal-v6/00-subnet.yaml, internal/controllers/subnet/tests/subnet-import-error/00-create-network.yaml, internal/controllers/subnet/tests/subnet-import/00-create-network.yaml
Misc changes that do not warrant separate pull requests.
=> Misc changes

internal/controllers/routerinterface/tests/routerinterface-create-minimal/00-assert.yaml, internal/controllers/routerinterface/tests/routerinterface-create-minimal/00-routerinterface.yaml, internal/controllers/routerinterface/tests/routerinterface-create-minimal/00-secret.yaml, internal/controllers/routerinterface/tests/routerinterface-create-minimal/README.md, kuttl-test.yaml
- Create a router,a network and a subnet.
- Import the router and the subnet.
- Create a RouterInterface from the imported subnet and router
=> routerinterface e2e

internal/controllers/port/actuator.go, internal/controllers/port/controller.go, internal/controllers/port/tests/port-import-dependency/02-create-port.yaml, internal/controllers/port/tests/port-import-dependency/03-assert.yaml, internal/controllers/port/tests/port-import-dependency/03-delete-network.yaml, internal/controllers/port/tests/port-import-dependency/04-assert.yaml, internal/controllers/port/tests/port-import-dependency/04-delete-port.yaml, internal/controllers/port/tests/port-import-dependency/README.md, internal/controllers/subnet/actuator.go, internal/controllers/subnet/controller.go, internal/controllers/subnet/tests/subnet-import-dependency/02-create-subnet.yaml, internal/controllers/subnet/tests/subnet-import-dependency/03-assert.yaml, internal/controllers/subnet/tests/subnet-import-dependency/03-delete-network.yaml, internal/controllers/subnet/tests/subnet-import-dependency/04-assert.yaml, internal/controllers/subnet/tests/subnet-import-dependency/04-delete-subnet.yaml, internal/controllers/subnet/tests/subnet-import-dependency/README.md
Only add deletion guards for the resources that ORC manages.
Fixes #315
=> Remove deletion guards from import deps

internal/controllers/generic/reconciler/controller.go, internal/controllers/generic/reconciler/resource_actions.go, internal/controllers/image/reconcile.go, internal/controllers/image/status.go, internal/controllers/image/upload.go, internal/controllers/image/webdownload.go, internal/controllers/network/status.go, internal/controllers/routerinterface/reconcile.go, internal/controllers/server/actuator.go, internal/logging/levels.go, internal/util/dependency/deletion_guard.go, internal/util/dependency/dependency.go, pkg/predicates/readiness.go
Define log levels.
Update log messages' verbosity
=> Update  log levels

website/docs/changelog.md, website/mkdocs.yml
Document releases, and breaking changes.
=> Add changelog

internal/controllers/routerinterface/reconcile.go
We were wrongly assuming that the device owner of a port for a router interface was always `network:router_interface`. This prevented ORC from creating a router interface for HA or DVR routers.
Fixes #330
=> Router interfaces: Account for more types of routers

api/v1alpha1/zz_generated.project-resource.go, internal/controllers/project/zz_generated.adapter.go, internal/controllers/project/zz_generated.controller.go
Regenerate go code introduced by
https://github.com/k-orc/openstack-resource-controller/pull/370 and missed in
https://github.com/k-orc/openstack-resource-controller/pull/374.
=> Fix lint job

SECURITY.md
While still not perfect, it at least highlights the supported versions and provides a way to securely report vulnerabilities.
Fixes #380.
=> Update security policy doc

go.mod, go.sum
Manual cherry-pick of https://github.com/k-orc/openstack-resource-controller/pull/381.
=> Bump x/net to fix GHSA-vvgc-356p-c3xw

api/v1alpha1/image_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/models-schema/zz_generated.openapi.go, config/crd/bases/openstack.k-orc.cloud_images.yaml, internal/controllers/image/actuator.go, internal/controllers/image/tests/image-import/00-import-resource.yaml, internal/controllers/image/tests/image-import/01-create-trap-resource.yaml, internal/controllers/image/tests/image-import/02-create-resource.yaml, pkg/clients/applyconfiguration/api/v1alpha1/imagefilter.go, pkg/clients/applyconfiguration/internal/internal.go, website/docs/crd-reference.md
Expose visibility field in ImageFilter and use it for both import/adoption.
closes #460
=> Image import: Visibility filter

README.md
This should have been part of
https://github.com/k-orc/openstack-resource-controller/pull/508.
=> Add missing volume controller to README
