.gitignore, config/samples/kustomization.yaml, config/samples/openstack_v1alpha1_openstackcloud.yaml, config/samples/openstack_v1alpha1_openstackflavor.yaml, config/samples/openstack_v1alpha1_openstackfloatingip.yaml, config/samples/openstack_v1alpha1_openstackimage.yaml, config/samples/openstack_v1alpha1_openstacknetwork.yaml, config/samples/openstack_v1alpha1_openstacksecuritygroup.yaml, config/samples/openstack_v1alpha1_openstacksecuritygrouprule.yaml, config/samples/openstack_v1alpha1_openstackserver.yaml, config/samples/openstack_v1alpha1_openstacksubnet.yaml
This creates a set of resources on the target OpenStack cloud.
Note that the floating IP is created but not used; the server is therefore not reachable from the outside yet.
**Howto:**
1. `make`
2. `make install`
3. `make run`
4. in a separate terminal: `cp ~/.config/openstack/clouds.yaml ./config/samples/`
5. replace the IDs of the existing external network, flavor, image in the CRDs
6. `kubectl apply -k ./config/samples/`
**To remove the resources from the cloud:**
1. comment out the cloud configuration in `kustomize`:
```yaml
generatorOptions:
disableNameSuffixHash: true
resources:
- openstack_v1alpha1_openstackflavor.yaml
- openstack_v1alpha1_openstackfloatingip.yaml
- openstack_v1alpha1_openstackimage.yaml
- openstack_v1alpha1_openstacknetwork.yaml
- …
```
=> config/samples: Populate with example data

.github/workflows/container_image.yaml
Prefix the commit SHA tag so that ephemeral builds are easier to spot in a list.
=> container image: Prefix commit builds

.github/workflows/container_image.yaml
This job was broken by a change in the variable identifiers that was not completely carried out.
=> ci: Fix image names

.github/workflows/website.yaml
Website building would fail on pull requests because the provider secret can't be used there.
=> actions: Only build website on main

api/v1alpha1/openstackflavor_types.go, api/v1alpha1/openstackimage_types.go, website/docs/design-decisions.md
IDs in OpenStack are also unique in time. Before this change, only the name of the Kubernetes resource was used to generate a deterministic OpenStack UUID. Which meant that once an image (or flavor) name was taken on a given cloud, it could never be recreated.
With this patch, the creation time of the Kubernetes resource is also used to compute a deterministic OpenStack UUID.
=> Image, Flavor: Compute a unique UUID

api/v1alpha1/flavor_types.go, cmd/models-schema/zz_generated.openapi.go, config/crd/bases/openstack.k-orc.cloud_flavors.yaml, pkg/clients/applyconfiguration/internal/internal.go, test/apivalidations/common_test.go, test/apivalidations/flavor_test.go, test/apivalidations/image_test.go
Check that a minimal flavor pass
Check that a flavor without RAM or VCPUs or with value 0 fails
Add validations for RAM and VCPUs to have a minimum
Check that a flavor with a description greater than 1024 fails
Move testCredentials to common_test
=> Add a basic test for flavor validation

Dockerfile
Switch to the go 1.23 builder as this is now the minimum version according to the go.mod, and change code paths to adapt to the new project structure so that we can build the binary.
=> Adapt Dockerfile to new project structure

.github/labeler.yml, .github/labels.yaml, .github/workflows/backport.yaml, .github/workflows/check-pr-labels.yaml, .github/workflows/ensure-labels.yaml, .github/workflows/label-issue.yaml, .github/workflows/label-pr.yaml
Copy and adapt relevant workflows from gophercloud to handle backporting to stable branches. Specifically:
* `ensure-labels.yaml` syncs labels defined in `.github/labels.yaml`
* `label-pr.yaml` runs go-apidiff on PRs and label them with a corresponding `semver:major`, `semver:minor`, or `semver:patch` label. Also labels PRs submitted to stable branches.
* `label-issue.yaml` clears the `needinfo` label on issues when the reported responded.
* `check-pr-labels.yaml` prevents merging PRs that have a `hold` label.
* `backport.yaml` effectively creates backports for PRs that have the `backport-v1.0` and `semver:patch` labels.
=> actions: Add backport automation tooling

.github/workflows/backport.yaml, .github/workflows/label-pr.yaml
We can no longer give write permission to the GITHUB_TOKEN globally and need to individually grant permissions to workflows. This should cover the workflows with the missing explicit permissions.
=> actions: Grant more permissions to workflows

internal/controllers/flavor/actuator.go, internal/controllers/flavor/controller.go, internal/controllers/flavor/reconcile.go, internal/controllers/generic/actuator.go, internal/controllers/image/actuator.go, internal/controllers/image/reconcile.go, internal/controllers/network/actuator.go, internal/controllers/network/controller.go, internal/controllers/network/reconcile.go, internal/controllers/port/actuator.go, internal/controllers/port/controller.go, internal/controllers/port/reconcile.go, internal/controllers/router/actuator.go, internal/controllers/router/controller.go, internal/controllers/router/reconcile.go, internal/controllers/securitygroup/actuator.go, internal/controllers/securitygroup/controller.go, internal/controllers/securitygroup/reconcile.go, internal/controllers/server/actuator.go, internal/controllers/server/reconcile.go
Fixes a bug in create where we were incorrectly polling while waiting on an ORC event.
Will allow us to wait on ORC router interface deletion when deleting a Subnet.
=> Allow Create and Delete to return WaitingOnEvent

internal/controllers/server/actuator.go
Stops, e.g. retrying when the flavor is too small for the image.
=> Server: Stop retrying for any non-retryable error

internal/controllers/image/actuator.go
We were only attempting adoption if there was no import stanza, which is not correct.
=> image: Fix adoption of previously created resource

.github/workflows/container_image.yaml
We don't want users to accidentally get nasty surprises on major bumps.
To follow the development branch, use `branch-main` tag instead, however you should know that we could introduce breaking changes at anytime in the development branch. You've been warned.
=> Stop pushing a latest tag for container images

api/v1alpha1/zz_generated.flavor-resource.go, api/v1alpha1/zz_generated.image-resource.go, api/v1alpha1/zz_generated.network-resource.go, api/v1alpha1/zz_generated.port-resource.go, api/v1alpha1/zz_generated.router-resource.go, api/v1alpha1/zz_generated.securitygroup-resource.go, api/v1alpha1/zz_generated.server-resource.go, api/v1alpha1/zz_generated.subnet-resource.go, cmd/resource-generator/data/api.template, config/crd/bases/openstack.k-orc.cloud_flavors.yaml, config/crd/bases/openstack.k-orc.cloud_images.yaml, config/crd/bases/openstack.k-orc.cloud_networks.yaml, config/crd/bases/openstack.k-orc.cloud_ports.yaml, config/crd/bases/openstack.k-orc.cloud_routers.yaml, config/crd/bases/openstack.k-orc.cloud_securitygroups.yaml, config/crd/bases/openstack.k-orc.cloud_servers.yaml, config/crd/bases/openstack.k-orc.cloud_subnets.yaml
This allows the user to do 'kubectl get openstack' to list all ORC OpenStack resources
of every type, e.g.:
```bash
$ kubectl get openstack
NAME                                                ID                                     AVAILABLE   MESSAGE                           AGE
flavor.openstack.k-orc.cloud/mbooth-cirros-flavor   5b2647a4-888f-4993-87c7-92851d21da01   True        OpenStack resource is available   49s
NAME                                               ID                                     AVAILABLE   MESSAGE                     AGE
image.openstack.k-orc.cloud/mbooth-cirros-cirros   d11a362a-a4c5-4141-b0d3-7ad41f486607   True        Glance image is available   49s
NAME                                                           ID …
```
=> Add all CRDs to the openstack category

api/v1alpha1/securitygroup_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/models-schema/zz_generated.openapi.go, config/crd/bases/openstack.k-orc.cloud_securitygroups.yaml, internal/controllers/securitygroup/actuator.go, pkg/clients/applyconfiguration/api/v1alpha1/securitygrouprule.go, pkg/clients/applyconfiguration/internal/internal.go
We don't want to dependend on Openstack resources, only on ORC resources
=> Remove RemoteGroupID from SecurityGroupRule

Makefile
We forgot to update the `build` and `run` targets after 690b760f49dfb61b173755e91cb51ed42472c7f3.
=> Fix build and run targets

api/v1alpha1/image_types.go, config/crd/bases/openstack.k-orc.cloud_images.yaml, test/apivalidations/image_test.go
Added compressed to ImageContainerFormat
Added a validation that cpuThreadPolicy should only be used when cpuPolicy is 'dedicated'
=> Add Image validation and an ImageContainerFormat

internal/controllers/flavor/actuator.go, internal/controllers/flavor/status.go, internal/controllers/generic/actuator.go, internal/controllers/generic/conditions.go, internal/controllers/generic/controller.go, internal/controllers/generic/progress_status.go, internal/controllers/generic/status.go, internal/controllers/image/actuator.go, internal/controllers/network/actuator.go, internal/controllers/network/status.go, internal/controllers/port/actuator.go, internal/controllers/port/status.go, internal/controllers/router/actuator.go, internal/controllers/router/status.go, internal/controllers/routerinterface/status.go, internal/controllers/securitygroup/actuator.go, internal/controllers/securitygroup/actuator_test.go, internal/controllers/securitygroup/status.go, internal/controllers/server/actuator.go, internal/controllers/server/status.go, internal/controllers/subnet/actuator.go, internal/controllers/subnet/status.go
This change makes accurately reporting the Progressing condition easier
to understand and more consistent across controllers.
Several methods previously returned a slice of WaitingOnEvent.
WaitingOnEvent is renamed to ProgressStatus to reflect its use.
Returning a ProgressStatus indicates that some operation is incomplete
and we are expecting to be called again.
We pass this slice of ProgressStatus to the status writer. We no longer
pass a progressMessage, so ProgressStatus is now the only way to report
Progressing.
We update the logic setting Progressing so that it only considers any
returned error, and ProgressStatus.
Consequently, the GetCommonStatus method of ResourceStatusWriter is now
renamed to ResourceIsAvailable (and its signature updated), as it no
longer pretends to report …
=> Improvements to Progressing condition

internal/controllers/network/actuator.go, internal/controllers/subnet/tests/create-full-v4/00-subnet.yaml, internal/controllers/subnet/tests/create-full-v6/00-subnet.yaml, internal/controllers/subnet/tests/create-minimal-v4/00-subnet.yaml, internal/controllers/subnet/tests/create-minimal-v6/00-subnet.yaml, internal/controllers/subnet/tests/import-error/00-create-network.yaml, internal/controllers/subnet/tests/import/00-create-network.yaml
We didn't check for the description to be set before converting to string which could result in a panic in the reconcile loop.
Fixes #187
=> Network: fix panic when creating resource without description

internal/controllers/network/actuator.go, internal/controllers/port/actuator.go, internal/controllers/router/actuator.go, internal/controllers/securitygroup/actuator.go, internal/controllers/subnet/actuator.go, internal/util/neutrontags/join.go
All neutron controllers had an almost identical reconciler for setting
and updating tags. We replace them all with a common implementation.
=> DRY updatetags reconciler

internal/controllers/flavor/tests/import-error/00-create-flavors.yaml
Drop the workaround for #185. We no longer need to specify a name in the spec to differentiate the resources.
=> CI: Drop workaround creating almost identical resources

internal/controllers/generic/controller.go
CR complains that ctrl.Result{} is not empty when returning an error.
=> Fix controller-runtime warning when DeleteResource returns error

api/v1alpha1/router_interface_types.go, config/crd/bases/openstack.k-orc.cloud_routerinterfaces.yaml
It was missing because it doesn't use the generated scaffolding.
=> Add routerinterface to openstack category

examples/bases/cirros/port.yaml, examples/bases/devstack/port.yaml, examples/bases/local-config-ref/kustomization.yaml, examples/local-config/kustomization.yaml, examples/local-config/securitygroup.yaml
Fixes issue of no networking in cirros and devstack examples.
=> examples: Import and use the default security group

.github/workflows/label-issue.yaml
It needs permission on pull requests as well.
=> CI: Give additional permissions to label-issue workflow

hack/e2e.sh, internal/controllers/flavor/tests/create-full/00-flavor.yaml, internal/controllers/flavor/tests/create-full/00-secret.yaml, internal/controllers/flavor/tests/create-minimal/00-flavor.yaml, internal/controllers/flavor/tests/create-minimal/00-secret.yaml, internal/controllers/flavor/tests/import-error/00-create-flavors.yaml, internal/controllers/flavor/tests/import-error/00-secret.yaml, internal/controllers/flavor/tests/import-error/01-import-flavor.yaml, internal/controllers/flavor/tests/import/00-import-flavor.yaml, internal/controllers/flavor/tests/import/00-secret.yaml, internal/controllers/flavor/tests/import/01-create-flavor.yaml, internal/controllers/subnet/tests/create-full-v4/00-secret.yaml, internal/controllers/subnet/tests/create-full-v4/00-subnet.yaml, internal/controllers/subnet/tests/create-full-v6/00-secret.yaml, internal/controllers/subnet/tests/create-full-v6/00-subnet.yaml, internal/controllers/subnet/tests/create-minimal-v4/00-secret.yaml, internal/controllers/subnet/tests/create-minimal-v4/00-subnet.yaml, internal/controllers/subnet/tests/create-minimal-v6/00-secret.yaml, internal/controllers/subnet/tests/create-minimal-v6/00-subnet.yaml, internal/controllers/subnet/tests/dependency/00-create-subnet.yaml, internal/controllers/subnet/tests/dependency/00-secret.yaml, internal/controllers/subnet/tests/dependency/01-create-network.yaml, internal/controllers/subnet/tests/import-error/00-create-network.yaml, internal/controllers/subnet/tests/import-error/00-create-subnets.yaml, internal/controllers/subnet/tests/import-error/00-secret.yaml, internal/controllers/subnet/tests/import-error/01-import-subnet.yaml, internal/controllers/subnet/tests/import/00-create-network.yaml, internal/controllers/subnet/tests/import/00-import-subnet.yaml, internal/controllers/subnet/tests/import/00-secret.yaml, internal/controllers/subnet/tests/import/01-create-subnet.yaml
We can now export the `E2E_OPENSTACK_CLOUD_NAME` and
`E2E_OPENSTACK_ADMIN_CLOUD_NAME` variables to override the default
credentials to use for tenant and admin operations during tests.
These default to `devstack` and `devstack-admin-demo` respectively.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/207
=> CI: Allows to override cloud names in tests

.github/dependabot.yml
release-1.0 will be released with CR 0.19 and k8s 0.31.
=> dependabot: ignore k8s & CR updates on release-1.0

internal/controllers/port/status.go, internal/controllers/routerinterface/reconcile.go, internal/controllers/routerinterface/status.go
Ports reports their statuses via a status field, we should take that
into consideration when computing if the port is available or not.
With this change, ports are reported as Available when the object has
a known ID for the resource, and the resource has ACTIVE or DOWN status.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/198
=> Port: Make port available based on its status

internal/controllers/generic/progress_status.go, internal/util/neutrontags/join.go
Fixes: #242
Combined with #247 this gives us the following output when watching a network with tags during provisioning:
```
mbooth-orc-managed-network
mbooth-orc-managed-network   9d88fa62-5195-403d-bfbe-da90a3353322
mbooth-orc-managed-network   9d88fa62-5195-403d-bfbe-da90a3353322   True        Resource status will be refreshed
mbooth-orc-managed-network   9d88fa62-5195-403d-bfbe-da90a3353322   True        Resource status will be refreshed
mbooth-orc-managed-network   9d88fa62-5195-403d-bfbe-da90a3353322   True        OpenStack resource is up to date
```
=> Neutron ReconcileTags returns NeedsRefresh

internal/controllers/network/tests/create-full/00-assert.yaml, internal/controllers/network/tests/create-full/00-network.yaml, internal/controllers/network/tests/import/01-assert.yaml
Now that #242 is fixed, we can re-enable these checks.
=> CI: Re-enable tag checks in network tests

internal/controllers/subnet/tests/create-full-v4/00-assert.yaml, internal/controllers/subnet/tests/create-full-v4/00-subnet.yaml, internal/controllers/subnet/tests/create-full-v6/00-assert.yaml, internal/controllers/subnet/tests/create-full-v6/00-subnet.yaml
`gateway: null` is different from gateway with type = None. It works as expected.
Closes #190
=> CI: Remove confusion about gateway in subnet tests

api/v1alpha1/zz_generated.port-resource.go, cmd/resource-generator/data/api.template, cmd/resource-generator/main.go, config/crd/bases/openstack.k-orc.cloud_ports.yaml
Adds an Addresses column to the kubectl print columns. Example output:
```
NAME                                            ID                                     AVAILABLE   ADDRESSES      MESSAGE
port.openstack.k-orc.cloud/mbooth-cirros-port   944efb42-8f58-473b-8582-e75f61cc92f3   True        10.0.185.190   OpenStack resource is up to date
```
If the port has multiple addresses they will all be displayed, space separated.
=> Add Addresses printcolumn to Ports

config/manager/manager.yaml
This patch updates the `manager.yaml` configuration file with the following changes:
- Enforces stricter security policies by explicitly setting:
- `runAsUser: 65532` and `runAsGroup: 65532` to define a non-root user for the manager container.
- `privileged: false` to ensure the container does not run with elevated privileges.
- `terminationMessagePolicy: FallbackToLogsOnError` for improved debugging.
- `seccompProfile: RuntimeDefault` to align with Kubernetes security best practices.
> [!NOTE]
> This change was inspired from upstream CAPO.
- Removed legacy comments and outdated recommendations related to Kubernetes versions < 1.19 and OpenShift < 4.11.
=> 🌱 Enhancements to Manager Deployment Configuration

.github/workflows/e2e.yaml, Makefile, hack/e2e.sh, hack/init_test_env.sh, hack/run_examples.sh
This makes it more user friendly for local development by allowing running the kuttl tests alone.
=> Split test-e2e make target into test-e2e and test-examples

.github/workflows/website.yaml, .gitignore, Makefile, website/Makefile, website/docs/crd-reference.md, website/mkdocs.yml
This removes some github actions magic by building the generated docs locally
and storing them in the repo.
Also fixes a bug in the verify-generated target where it wouldn't return a
failure for an untracked file.
=> Build CRD reference docs from Makefile

api/v1alpha1/image_types.go, api/v1alpha1/network_types.go, api/v1alpha1/port_types.go, api/v1alpha1/router_interface_types.go, api/v1alpha1/router_types.go, api/v1alpha1/securitygroup_types.go, api/v1alpha1/server_types.go, api/v1alpha1/subnet_types.go, config/crd/bases/openstack.k-orc.cloud_images.yaml, config/crd/bases/openstack.k-orc.cloud_networks.yaml, config/crd/bases/openstack.k-orc.cloud_ports.yaml, config/crd/bases/openstack.k-orc.cloud_routerinterfaces.yaml, config/crd/bases/openstack.k-orc.cloud_routers.yaml, config/crd/bases/openstack.k-orc.cloud_securitygroups.yaml, config/crd/bases/openstack.k-orc.cloud_servers.yaml, config/crd/bases/openstack.k-orc.cloud_subnets.yaml
Until we implement mutability for the different resources, add a CEL validation that enforce immutability, to avoid confusion.
=> Make ResourceSpec immutable until they are truly mutable

internal/controllers/port/controller.go
Default subnets and securityGroups to an empty slice of strings.
Fixes: #298
=> Port Set subnets and securityGroups to empty slice

internal/controllers/flavor/status.go, internal/controllers/generic/interfaces/status.go, internal/controllers/generic/status/conditions.go, internal/controllers/generic/status/status.go, internal/controllers/network/status.go, internal/controllers/port/status.go, internal/controllers/router/status.go, internal/controllers/routerinterface/status.go, internal/controllers/securitygroup/status.go, internal/controllers/server/status.go, internal/controllers/subnet/status.go
This PR makes 2 changes to ResourceStatusWriter and adds godoc.
- **Replace GetApplyConfigConstructor with GetApplyConfig**
This removes a level of indirection in ResourceStatusWriter.
- **Replace ResourceIsAvailable with ResourceAvailableStatus**
This allows us to write an Unknown status for the Available condition.
=> Usability improvements to ResourceStatusWriter

internal/controllers/port/controller.go, internal/controllers/port/tests/port-create-full/00-assert.yaml, internal/controllers/port/tests/port-create-full/00-port.yaml, internal/controllers/port/tests/port-create-full/00-prerequisites.yaml, internal/controllers/port/tests/port-create-full/README.md, internal/controllers/port/tests/port-create-minimal/00-assert.yaml, internal/controllers/port/tests/port-create-minimal/00-port.yaml, internal/controllers/port/tests/port-create-minimal/00-prerequisites.yaml, internal/controllers/port/tests/port-create-minimal/01-assert.yaml, internal/controllers/port/tests/port-create-minimal/01-delete-secret.yaml, internal/controllers/port/tests/port-create-minimal/README.md, internal/controllers/port/tests/port-import-error/00-assert.yaml, internal/controllers/port/tests/port-import-error/00-create-port.yaml, internal/controllers/port/tests/port-import-error/00-prerequisites.yaml, internal/controllers/port/tests/port-import-error/01-assert.yaml, internal/controllers/port/tests/port-import-error/01-import-port.yaml, internal/controllers/port/tests/port-import-error/README.md, internal/controllers/port/tests/port-import/00-assert.yaml, internal/controllers/port/tests/port-import/00-import-port.yaml, internal/controllers/port/tests/port-import/00-prerequisites.yaml, internal/controllers/port/tests/port-import/01-assert.yaml, internal/controllers/port/tests/port-import/01-create-trap-port.yaml, internal/controllers/port/tests/port-import/02-assert.yaml, internal/controllers/port/tests/port-import/02-create-port.yaml, internal/controllers/port/tests/port-import/README.md, kuttl-test.yaml
- Introduced new kuttl-based end-to-end tests for the Port controller.
- Added test cases for:
- Creating a full-featured Port (`create-full`).
- Creating a minimal Port (`create-minimal`).
- Handling errors when multiple matching Ports exist (`import-error`).
- Importing a Port with a filtering mechanism (`import`).
- Each test suite includes:
- Port YAML definitions.
- Assertions to validate expected behavior.
- Secrets creation for cloud credentials.
- Updated `kuttl-test.yaml` to include the Port test suite.
These tests ensure that Port resources are properly created, imported, and validated against OpenStack environments.
=> Add kuttl tests for Port controller

website/docs/development/godoc/generic-interfaces.md
The `make-generate` job for
https://github.com/k-orc/openstack-resource-controller/pull/302 ran against a version of orc that didn't include generated interface docs. This causes the it to fail on the main branch.
=> Fix generated docs

website/docs/development/writing-tests.md
Improve the e2e docs:
- add general considerations when writing kuttl tests
- add description and testing pattern for all expected tests
- give tips for running kubectl or openstack commands in the tests
- explain how to run tests locally
=> Docs: Improve kuttl docs

README.md, RELEASE.md, website/docs/getting-started.md
The previously documented method for deploying ORC does not work with v2 as it is missing a kustomization file:
```
$ export ORC_RELEASE="https://github.com/k-orc/openstack-resource-controller/dist?ref=v2.0.2"
$ kubectl apply --server-side -k $ORC_RELEASE
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/kustomize-50497731/dist'
```
Instead, point to the `install.yaml` from the latest released artifact.
=> Update installation method in getting started docs

Makefile, api/v1alpha1/securitygroup_types.go, config/crd/bases/openstack.k-orc.cloud_securitygroups.yaml, test/apivalidations/securitygroup_test.go
We were using a CEL function that is not available until kubernetes 1.31. Drop the validation to restore kubernetes 1.29 compatibility, and adjust the kubernetes version in the envtest so that we can catch such issues in the future.
We can revert this commit once we bump the minimal required version of kubernetes to be 1.31.
=> Restore kube 1.29 compatibility

README.md
We've technically implemented security group rules as part of the security group object, and they don't have dedicated objects, but it is still worth documenting as supported in the README.
Also create a separate column for v2.x now that it is released.
Fixes #344
=> README: Add security group rule

.github/workflows/container_image.yaml, .github/workflows/release_image.yaml
Leverage docker builx to build multi-platform images supporting `linux/amd64` and `linux/arm64` architectures.
Fixes #352
=> Build multi-platform images

internal/osclients/compute.go, internal/osclients/loadbalancer.go, internal/osclients/mock/compute.go, internal/osclients/mock/loadbalancer.go, internal/osclients/mock/networking.go, internal/osclients/mock/volume.go, internal/osclients/networking.go, internal/osclients/volume.go, internal/scope/client.go, internal/scope/provider.go
Use a client capable of sending the reconcile ID as the request ID for
all OpenStack API calls. This makes it possible to correlate ORC and
OpenStack logs.
For https://github.com/k-orc/openstack-resource-controller/issues/218.
=> Set request ID for all API calls

cmd/resource-generator/data/adapter.template, internal/controllers/flavor/actuator.go, internal/controllers/flavor/zz_generated.adapter.go, internal/controllers/image/actuator.go, internal/controllers/image/zz_generated.adapter.go, internal/controllers/network/actuator.go, internal/controllers/network/zz_generated.adapter.go, internal/controllers/port/actuator.go, internal/controllers/port/zz_generated.adapter.go, internal/controllers/router/actuator.go, internal/controllers/router/zz_generated.adapter.go, internal/controllers/securitygroup/actuator.go, internal/controllers/securitygroup/zz_generated.adapter.go, internal/controllers/server/actuator.go, internal/controllers/server/zz_generated.adapter.go, internal/controllers/subnet/actuator.go, internal/controllers/subnet/zz_generated.adapter.go
This created inflexibility for any API with different name constraints
to those specified on OpenStackName.
Additionally, every caller of it was already casting the result to
string.
=> Change return of getResourceName to string

.github/workflows/go-lint.yaml, Makefile, api/v1alpha1/zz_generated.flavor-resource.go, api/v1alpha1/zz_generated.image-resource.go, api/v1alpha1/zz_generated.network-resource.go, api/v1alpha1/zz_generated.port-resource.go, api/v1alpha1/zz_generated.router-resource.go, api/v1alpha1/zz_generated.securitygroup-resource.go, api/v1alpha1/zz_generated.server-resource.go, api/v1alpha1/zz_generated.subnet-resource.go, cmd/resource-generator/data/adapter.template, cmd/resource-generator/data/api.template, cmd/resource-generator/data/controller.template, internal/controllers/flavor/zz_generated.adapter.go, internal/controllers/flavor/zz_generated.controller.go, internal/controllers/image/zz_generated.adapter.go, internal/controllers/image/zz_generated.controller.go, internal/controllers/network/zz_generated.adapter.go, internal/controllers/network/zz_generated.controller.go, internal/controllers/port/zz_generated.adapter.go, internal/controllers/port/zz_generated.controller.go, internal/controllers/router/zz_generated.adapter.go, internal/controllers/router/zz_generated.controller.go, internal/controllers/securitygroup/zz_generated.adapter.go, internal/controllers/securitygroup/zz_generated.controller.go, internal/controllers/server/zz_generated.adapter.go, internal/controllers/server/zz_generated.controller.go, internal/controllers/subnet/zz_generated.adapter.go, internal/controllers/subnet/zz_generated.controller.go
This patch:
* Fixes the templates for resource generation, so that they output formatted code;
* Re-generates the resources
* Adds a gofmt check to the `go-lint` test
=> Format Go code

go.mod, go.sum
I'm not sure why it wasn't updated by dependabot in https://github.com/k-orc/openstack-resource-controller/pull/368. Maybe because it is indirect?
Anyway, this addresses GHSA-vvgc-356p-c3xw
=> Bump x/net to fix GHSA-vvgc-356p-c3xw

.golangci.yml, Makefile, api/v1alpha1/image_types.go, api/v1alpha1/securitygroup_types.go
The project moved to sigs.k8s.io and changed name to kube-api-linter.
Fixes one new offense (not changing our public API), and enable the new `nomaps` linter.
=> Bump kube-api-linter

hack/collectlogs
Leftover objects after the kuttl tests were not collected since they are created in different namespaces. We should colllect objects from all namespaces.
=> CI: Collect objects from all namespaces

kuttl-test.yaml
This was missing from https://github.com/k-orc/openstack-resource-controller/pull/370.
=> CI: enable project e2e tests

.github/workflows/e2e.yaml, .github/workflows/weekly-security-scan.yaml, .gitignore, Dockerfile, Makefile, hack/ensure-trivy.sh, hack/verify-container-images.sh
This adds a new make target "verify-security" that runs govulncheck agains the code base and also builds the contaier image and scans it with trivy. I tried keeping things similar to how they are done elsewhere in the code. This is all based on how they do it in Cluster API (hence the copyright text in the scripts).
Probably the most controversial thing here is that I added the GO_VERSION variable. The idea is to make sure we know what exact version is used.
=> Add weekly security scan using govulncheck and trivy

internal/controllers/subnet/actuator.go, internal/controllers/subnet/controller.go, internal/controllers/subnet/tests/subnet-dependency/00-assert.yaml, internal/controllers/subnet/tests/subnet-dependency/02-assert.yaml
Whenever the subnet has a routerRef, it needs to be able to wait for the resource to be available.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/316.
=> Subnet: Add dependency on router

Makefile
As you can see, I got the "prerequisite" wrong for the verify-govulncheck target in the Makefile.
https://github.com/k-orc/openstack-resource-controller/actions/runs/15108667183/job/42462914639#step:5:192
I had govulncheck already installed when I tried it locally, so of course I didn't catch it...
=> Fix verify-govulncheck

api/v1alpha1/floatingip_types.go
New FloatingIP type has an optional field in resource.spec called `FloatingIP` but it's currently missing `omitempty` json tag, which causes issues when trying to create a new instance using server side apply with this field in null
=> FloatingIP: set omitempty for resource.floatingIP

internal/controllers/image/status.go
This fixes the import of image, where the status may not reflect the real status of the resource. This is essentially the same fix as for [1], but for images.
We didn't see failures in our CI, presumably because we're using very small images, however this was seen in CAPO, when bumping to ORC 2.1.0 [2].
[1] https://github.com/k-orc/openstack-resource-controller/issues/280
[2] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2552
=> image: Poll until image is ready

api/v1alpha1/credentials_ref.go, internal/scope/provider.go
Move constants for CloudCredentials secret keys to the api package so they can be imported from external repositories.
Closes #413
=> CloudCredential secret: export constants in api

internal/controllers/routerinterface/controller.go, internal/controllers/routerinterface/reconcile.go, internal/controllers/routerinterface/tests/routerinterface-create-minimal/00-create-resource.yaml
This hopefully fixes a deadlock situation where an unmanaged router is not
available due to the backing router being deleted in OpenStack, causing
the router interface to not reconcile, and preventing the router
deletion due to pending finalizer.
While I was looking at router interface, I also made the object names more consistent with other tests in the `routerinterface-create-minimal` test, and used a consistent name for logging, as it appeared as `routerinterface` or `router_interface` in the logs, depending on the event generating the log.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/378.
=> Router interface: reconcile interfaces for routers pending deletion

.github/workflows/e2e.yaml
Fixes the following error while deploying devstack:
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/libv/libvpx/libvpx7_1.11.0-2ubuntu2.3_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
=> CI: Bump devstack-action

.github/workflows/container_image.yaml
Using a label only works for image manifests, while using an annotation works for both image manifests and image indexes. For multi-arch builds, we need to use an annotation to set an expiration date.
Fixes #433
=> Use annotation to add expiration for images in quay

api/v1alpha1/subnet_types.go, config/crd/bases/openstack.k-orc.cloud_subnets.yaml, internal/controllers/generic/reconciler/controller.go, internal/controllers/subnet/actuator.go, internal/controllers/subnet/actuator_test.go, internal/controllers/subnet/tests/subnet-create-full-v4/00-assert.yaml, internal/controllers/subnet/tests/subnet-update/00-assert.yaml, internal/controllers/subnet/tests/subnet-update/00-minimal-resource.yaml, internal/controllers/subnet/tests/subnet-update/00-prerequisites.yaml, internal/controllers/subnet/tests/subnet-update/01-assert.yaml, internal/controllers/subnet/tests/subnet-update/01-updated-resource.yaml, internal/controllers/subnet/tests/subnet-update/02-assert.yaml, internal/controllers/subnet/tests/subnet-update/02-reverted-resource.yaml
Allow mutability for all the fields available in gophercloud's subnet UpdateOpts stucture, except for `dnsPublishFixedIP` that we have explicitly left immutable to avoid potential endless reconciliation.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/275
=> Subnet: add mutability for a fields that support it

Makefile
This addresses three vulnerabilities in the standard library:
- [GO-2025-3751](https://pkg.go.dev/vuln/GO-2025-3751)
- [GO-2025-3750](https://pkg.go.dev/vuln/GO-2025-3750)
- [GO-2025-3749](https://pkg.go.dev/vuln/GO-2025-3749)
Found by the weekly security scan: https://github.com/k-orc/openstack-resource-controller/actions/runs/15676365940/job/44157504655
=> Bump go to 1.23.10

.github/workflows/go-lint.yaml, .github/workflows/label-pr.yaml, .github/workflows/unit.yml
This ensures ORC remains compatible with the go version we claim it supports.
=> Use pinned go version for CI

.github/workflows/check-pr-labels.yaml, .github/workflows/e2e.yaml, .github/workflows/generate.yaml, .github/workflows/go-lint.yaml, .github/workflows/unit.yml
In preparation for enabling merge queues in this repository, we need to update the required workflows to be triggered on `merge_group` events.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
Related to #220
=> Prepare for enabling merge-queues

.github/dependabot.yml
The bump of "github.com/onsi/gomega" from 1.38.0 to 1.38.1 requires go 1.24, while we're still on 1.23.
=> dependabot: ignore modules requiring go1.24

api/v1alpha1/server_types.go, config/crd/bases/openstack.k-orc.cloud_servers.yaml, internal/controllers/server/actuator.go, internal/controllers/server/actuator_test.go, internal/controllers/server/tests/server-update/00-assert.yaml, internal/controllers/server/tests/server-update/00-minimal-resource.yaml, internal/controllers/server/tests/server-update/00-prerequisites.yaml, internal/controllers/server/tests/server-update/01-assert.yaml, internal/controllers/server/tests/server-update/01-updated-resource.yaml, internal/controllers/server/tests/server-update/02-assert.yaml, internal/controllers/server/tests/server-update/02-reverted-resource.yaml, internal/osclients/compute.go, internal/osclients/mock/compute.go
Allow mutability for all the fields available in gophercloud's server `UpdateOpts` structure.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/470
=> Server: add mutability for all fields that support it

Makefile
This addresses GO-2025-3956.
See https://pkg.go.dev/vuln/GO-2025-3956 for details.
=> Bump go to 1.23.12

api/v1alpha1/router_types.go, config/crd/bases/openstack.k-orc.cloud_routers.yaml, internal/controllers/router/actuator.go, internal/controllers/router/actuator_test.go, internal/controllers/router/tests/router-update/00-assert.yaml, internal/controllers/router/tests/router-update/00-minimal-resource.yaml, internal/controllers/router/tests/router-update/00-prerequisites.yaml, internal/controllers/router/tests/router-update/01-assert.yaml, internal/controllers/router/tests/router-update/01-updated-resource.yaml, internal/controllers/router/tests/router-update/02-assert.yaml, internal/controllers/router/tests/router-update/02-reverted-resource.yaml
Allow mutability for all the fields available in gophercloud's flavor UpdateOpts structure.
Fixes: https://github.com/k-orc/openstack-resource-controller/issues/468
=> Router: add mutability for all fields that support it

internal/controllers/server/actuator.go
For some reason, gophercloud returns server tags as a pointer to a slice of strings. It could be nil if the server has no tags yet. We need to properly deref it.
Fixes https://github.com/k-orc/openstack-resource-controller/issues/529.
=> Server: Fix a panic during tag reconcile
